### ISSUE TITLE
HF app is crashing on a tablet

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-hf#110]
Health Facility app is crashing when opening on a tablet, specifically when:
1. Click House Location row from ANC Register Profile
2. Clicking on a client in the FP Register
3. Clicking on Service Activity Reporting (https://github.com/OpenSRP/opensrp-client-reporting/issues/106)

**Comment by manutarus** [comment]
@msschroeder do we know which tablet they are using? trying to replicate

**Comment by msschroeder** [comment]
@manutarus @allan-allay Galaxy Tab A (2016)

**Comment by allan-on** [comment]
@msschroeder Is it possible to get the version of Android that was running on the tablet?

**Comment by msschroeder** [comment]
Android version is 5.1.1

**Comment by ellykits** [comment]
@msschroeder I have tested this using Samsung Galaxy Tab A (2016) Android version 5.1.1. Using release apk and the staging server and unable to reproduce the bug. Am not sure if the crash was related to syncing referrals which I have fixed.

**Comment by msschroeder** [comment]
@ellykits The only one that remains right now is 2. When you click on a FP client (any client) it will still freeze

**Comment by ellykits** [comment]
This issue should now be resolved @msschroeder .We were able to reproduce the bug that was causing app crash when you open Family Planning member profile and had it fixed.

**Comment by msschroeder** [comment]
Looks great! Good job!
